version: 2
updates:
  # Enable version updates for go
  - package-ecosystem: "gomod"
    # Look for a `go.mod` in the `root` directory
    directory: "/"
    # Check for updates daily
    schedule:
      interval: "daily"

